@startuml packages_game
set namespaceSeparator none
package "modules" as modules {
}
package "modules.audio" as modules.audio {
}
package "modules.audio.audio_manager" as modules.audio.audio_manager {
}
package "modules.config" as modules.config {
}
package "modules.config.settings" as modules.config.settings {
}
package "modules.config.theme" as modules.config.theme {
}
package "modules.constants" as modules.constants {
}
package "modules.display" as modules.display {
}
package "modules.editor" as modules.editor {
}
package "modules.effects" as modules.effects {
}
package "modules.effects.score" as modules.effects.score {
}
package "modules.effects.score.bonus_rules" as modules.effects.score.bonus_rules {
}
package "modules.effects.score.score_manager" as modules.effects.score.score_manager {
}
package "modules.engine" as modules.engine {
}
package "modules.entities" as modules.entities {
}
package "modules.entities.actuators" as modules.entities.actuators {
}
package "modules.entities.actuators.actuator_base" as modules.entities.actuators.actuator_base {
}
package "modules.entities.actuators.flipper" as modules.entities.actuators.flipper {
}
package "modules.entities.actuators.plunger" as modules.entities.actuators.plunger {
}
package "modules.entities.ball" as modules.entities.ball {
}
package "modules.entities.obstacles" as modules.entities.obstacles {
}
package "modules.entities.obstacles.bumper" as modules.entities.obstacles.bumper {
}
package "modules.entities.obstacles.hole" as modules.entities.obstacles.hole {
}
package "modules.entities.obstacles.obstacle_base" as modules.entities.obstacles.obstacle_base {
}
package "modules.entities.obstacles.target" as modules.entities.obstacles.target {
}
package "modules.entities.player" as modules.entities.player {
}
package "modules.entities.tiles" as modules.entities.tiles {
}
package "modules.events" as modules.events {
}
package "modules.events.actions" as modules.events.actions {
}
package "modules.events.io" as modules.events.io {
}
package "modules.game" as modules.game {
}
package "modules.input" as modules.input {
}
package "modules.input.input_handler" as modules.input.input_handler {
}
package "modules.physics" as modules.physics {
}
package "modules.physics.collision_manager" as modules.physics.collision_manager {
}
package "modules.physics.physics_engine" as modules.physics.physics_engine {
}
package "modules.physics.trajectory_controller" as modules.physics.trajectory_controller {
}
package "modules.ui" as modules.ui {
}
package "modules.ui.background" as modules.ui.background {
}
package "modules.ui.menu" as modules.ui.menu {
}
package "modules.ui.panel" as modules.ui.panel {
}
package "modules.ui.stage" as modules.ui.stage {
}
package "modules.utils" as modules.utils {
}
modules.display --> modules.constants
modules.engine --> modules.display
modules.engine --> modules.events.actions
modules.engine --> modules.events.io
modules.engine --> modules.game
modules.entities.actuators.flipper --> modules.entities.actuators.actuator_base
modules.entities.actuators.plunger --> modules.entities.actuators.actuator_base
modules.entities.obstacles.bumper --> modules.entities.obstacles.obstacle_base
modules.entities.obstacles.hole --> modules.entities.obstacles.obstacle_base
modules.entities.obstacles.target --> modules.entities.obstacles.obstacle_base
modules.game --> modules.display
modules.game --> modules.entities.player
modules.game --> modules.entities.tiles
modules.game --> modules.ui.panel
modules.game --> modules.ui.stage
modules.physics.trajectory_controller --> modules.physics.collision_manager
modules.ui.stage --> modules.ui.background
@enduml
